# meta-connectivity — Yocto layer for USB Manager / Connectivity SC prototype

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "connectivity"
BBFILE_PATTERN_connectivity = "^${LAYERDIR}/"
BBFILE_PRIORITY_connectivity = "10"

LAYERDEPENDS_connectivity = "core"
LAYERSERIES_COMPAT_connectivity = "scarthgap nanbield kirkstone"

# Monorepo source path for usb-manager externalsrc recipe
USB_MANAGER_SRCDIR := "${LAYERDIR}/../usb-manager"
