# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "cm3-usb"
BBFILE_PATTERN_cm3-usb = "^${LAYERDIR}/"
BBFILE_PRIORITY_cm3-usb = "10"

LAYERDEPENDS_cm3-usb = "core raspberrypi"
LAYERSERIES_COMPAT_cm3-usb = "scarthgap"
